### PR TITLE
[TS-BR | Master] LPS-110839 resetting value of hidden field by a form rule

### PR DESCRIPTION
**Pull request by rijema**
Just a quick test.

[Click here to see the LPS](https://issues.liferay.com/browse/LPS-110839)

### CODE REVIEW

**Comment by rijema** [comment]
@linolaoj can you take a look at this? My main goal is to follow the description that Renato said [in this comment](https://issues.liferay.com/browse/PTR-1582?focusedCommentId=2112369&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-2112369)

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
Hi @rijema, it looks good to me. You can send me a pull request to run the tests.
Thanks!

**Comment by michaelhashimoto** [comment]
ci:help

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by michaelhashimoto** [comment]
@rijema - If I try to see your collaborators as @liferay-continuous-integration it does not work:

<pre>michaelhashimoto@Hashis-MacBook-Pro /opt/dev/projects/github/liferay-jenkins-ee$ curl -H 'Authorization: token xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx' https://api.github.com/repos/rijema/liferay-portal/collaborators
{
  "message": "Must have push access to view repository collaborators.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#list-repository-collaborators"
}</pre>

I did the same test against another user's repository as @liferay-continuous-integration and it worked.

If @liferay-continuous-integration is a collaborator for this [repository](https://github.com/rijema/liferay-portal/), then another thing you can check is if your account is a public account:
https://docs.github.com/en/github/setting-up-and-managing-your-github-user-account/publicizing-or-hiding-organization-membership

Let me know if you still are running into issues.

Thanks!

**Comment by rijema** [comment]
Hi @michaelhashimoto , thanks for helping me with this!

Actually in my account settings it's saying that I have liferay-continuous-integration as a collaborator . Here is a screenshot of my liferay-portal repo settings. The visibility of  my membership is public, I can run tests in my liferay-portal-ee repository. Should I take some specific step to activate the CI as a collaborator?

6AD447A5-B7EA-41BE-8C91-D0C81D9E7EA3
6C22F893-26B9-4010-80AF-37378CF46A96

Best.

**Comment by michaelhashimoto** [comment]
@rijema - Hmm.. This doesn't make sense.  I wonder if it's a GitHub bug, can you try removing @liferay-continuous-integration as a collaborator.  And then re-adding him?  I did a direct curl and it still did not work which leads me to believe that it's something on GitHub's end.

**Comment by michaelhashimoto** [comment]
@rijema - I made a ticket to GitHub, I have one random idea.  Can you try to remove @liferay-continuous-integration as a collaborator, and then re-add him?  I am wondering if there was just a small outage when the request was made.  I'll also try asking my team to see what else could be the issue.

Thanks for your patience.

**Comment by michaelhashimoto** [comment]
ci:test:relevant

**Comment by rijema** [comment]
Done, @michaelhashimoto. 
48FFBBA8-97E8-4DCC-88F1-8500F22ADBA3_4_5005_c
After the status change of pending invite to collaborator I will rerun the tests and give you a feedback.

**Comment by michaelhashimoto** [comment]
@rijema - it works now!  Thanks!  I'm not sure if it was your re-approval or if GitHub fixed it.  Oh well.  As a side, for future CI issue you can contact us in the #ci channel in slack.

https://liferay.slack.com/archives/C19PWQ74J

**Comment by rijema** [comment]
Thank you very much for your help, @michaelhashimoto!

**Pull request closed without merging**
