### PR TITLE
LPS-110839 not using value of hidden field for rule evaluation

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:test:sf

**Comment by linolaoj** [comment]
ci:test:relevant

**Comment by linolaoj** [comment]
ci:stop

**Comment by rijema** [comment]
ci:test:sf

**Comment by rijema** [comment]
Hi @linolaoj , just took a few days of PTO as you can see. Starting as soon as I can the review 
[👍](https://emojipedia.org/thumbs-up)

image

**Pull request closed without merging**
